version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      timezone: America/Panama

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      timezone: America/Panama
